import Head from "next/head";
import Navbar from "~/components/Navbar";
import Link from "next/link";
import Image from "next/image";

export default function Home() {

  return (
    <>
      <Head>
        <title>Dungeon Drawings</title>
        <meta name="A platform to bring your imagination to life" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-between bg-custom bg-cover bg-center bg-no-repeat px-10">
        <Navbar />
        <div className="md:flex items-center justify-center gap-6">
          <div className="flex justify-center">
            <div className="max-w-[65%]">
              <h1 className="text-4xl font-bold tracking-tight text-text ">
                Welcome to
              </h1>
              <h1 className="text-accent text-6xl font-bold tracking-tight sm:text-[5rem] mt-6">Dungeon</h1>
              <h1 className="text-accent text-6xl font-bold tracking-tight sm:text-[5rem]">Drawings</h1>
              <div className="mt-10 text-text text-2xl">
                Bring your imagination to life with the power of AI
              </div>
              <Link href='/Selection' passHref>
                <button className="border-accent rounded-md py-4 px-8 bg-accent text-bg mt-6 text-xl hover:shadow-blueGlow transition-all duration-300 ease-in-out">
                  Get Started
                </button>
              </Link>
            </div>
          </div>
          <div className="border-2 rounded-xl overflow-hidden border-accent shadow-sBlueGlow transition-all duration-300">
            <Image 
              src='/dalle-1.png'
              width={400}
              height={533.3333}
              alt=''
            />
          </div>
        </div>
        <div className="text-xl text-text pb-6">Powered by DALL-E</div>
      </main>
    </>
  );
}
