import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";

export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Dungeon Drawings</title>
        <meta name="A platform to bring your imagination to life" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-linear">
        <div className="px-4 py-16 ">
          <div className="flex justify-start">
            <h1 className="text-4xl font-bold tracking-tight text-text ">
            Welcome to
            </h1>
          </div>
          <h1 className="text-accent text-6xl font-bold tracking-tight sm:text-[5rem] mt-6">Dungeon</h1>
          <h1 className="text-accent text-6xl font-bold tracking-tight sm:text-[5rem]">Drawings</h1>
          <div className="mt-10 text-text text-2xl max-w-[70%]">
            Bring your imagination to life with the power of AI
          </div>
          <button className="border-accent rounded-md py-4 px-8 bg-accent text-bg mt-6 text-xl opacity-70 hover:opacity-100 transition-opacity duration-300 ease-in-out">
            Get Started
          </button>
        </div>
      </main>
    </>
  );
}
